---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-ingress-watcher
  namespace: kuma-ingress-watcher
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: kuma-ingress-watcher
  template:
    metadata:
      labels:
        app: kuma-ingress-watcher
    spec:
      serviceAccountName: kuma-ingress-watcher
      containers:
        - name: controller
          ports:
            - containerPort: 4025
              protocol: TCP
          image: "ghcr.io/squent/kuma-ingress-watcher:1.5.0"
          stdin: true
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: UPTIME_KUMA_URL
              value: "https://down.crt.house"
            - name: WATCH_INTERVAL
              value: "60"
            - name: WATCH_INGRESSROUTES
              value: "false"
            - name: WATCH_INGRESS
              value: "true"
            - name: UPTIME_KUMA_USER
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-credentials
                  key: user
            - name: UPTIME_KUMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-credentials
                  key: password
