---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uptime-kuma-credentials
  namespace: kuma-ingress-watcher
spec:
  target:
    name: uptime-kuma-credentials
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 0cebfed1-6235-4008-9bd6-c3635e446300
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 0cebfed1-6235-4008-9bd6-c3635e446300
        metadataPolicy: None
        property: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
