---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuma-ingress-watcher
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuma-ingress-watcher
subjects:
  - kind: ServiceAccount
    name: kuma-ingress-watcher
    namespace: kuma-ingress-watcher
roleRef:
  kind: ClusterRole
  name: kuma-ingress-watcher
  apiGroup: rbac.authorization.k8s.io
