---
apiVersion: v1
kind: Secret
metadata:
  name: kuma-ingress-watcher
  namespace: kuma-ingress-watcher
  annotations:
    kubernetes.io/service-account.name: kuma-ingress-watcher
type: kubernetes.io/service-account-token
